<a href="https://colab.research.google.com/github/amilsiddik/machine-Learning/blob/main/03_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Preprocessing**

Sample Data

In [1]:
import numpy as np
from sklearn import preprocessing
sample_data = np.array([[2.1,-1.0,4.5],
                       [-1.5,2.4,3.5],
                       [0.5,-0.7,5.6],
                       [5.9,2.3,-5.8]])
sample_data

array([[ 2.1, -1. ,  4.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -0.7,  5.6],
       [ 5.9,  2.3, -5.8]])

1. Binarisation

In [2]:
sample_data

array([[ 2.1, -1. ,  4.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -0.7,  5.6],
       [ 5.9,  2.3, -5.8]])

In [3]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

2. Scaling

In [3]:
sample_data

array([[ 2.1, -1. ,  4.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -0.7,  5.6],
       [ 5.9,  2.3, -5.8]])

In [8]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0,1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.        , 0.90350877],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.08823529, 1.        ],
       [1.        , 0.97058824, 0.        ]])

In [9]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.        , 0.90350877],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.08823529, 1.        ],
       [1.        , 0.97058824, 0.        ]])

Normalisasi **L1** Least Absolute Deviation

In [10]:
sample_data

array([[ 2.1, -1. ,  4.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -0.7,  5.6],
       [ 5.9,  2.3, -5.8]])

In [11]:
l1_normalised_data=preprocessing.normalize(sample_data,norm='l1')
l1_normalised_data

array([[ 0.27631579, -0.13157895,  0.59210526],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.07352941, -0.10294118,  0.82352941],
       [ 0.42142857,  0.16428571, -0.41428571]])

Normalisasi **L2** Least Squares

In [12]:
sample_data

array([[ 2.1, -1. ,  4.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -0.7,  5.6],
       [ 5.9,  2.3, -5.8]])

In [13]:
l2_normalised_data=preprocessing.normalize(sample_data,norm='l2')
l2_normalised_data

array([[ 0.41456341, -0.19741115,  0.88835017],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.08825056, -0.12355079,  0.98840631],
       [ 0.68706914,  0.26784051, -0.6754239 ]])