<a href="https://colab.research.google.com/github/amilsiddik/machine-Learning/blob/main/06_Regression_dengan_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sample Dataset**

In [58]:
import pandas as pd

sensus = {
    'tinggi' : [158,170,183,191,155,163,180,158,170],
    'jk' :[
           'pria','pria','pria','pria','wanita','wanita','wanita','wanita','wanita'
    ],
    'berat' : [64,86,84,80,49,59,67,54,67]
}
sensus_df=pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     170  wanita     67

Features & Target

In [59]:
import numpy as np

X_train = np.array(sensus_df[['tinggi','jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train : \n{X_train}\n')
print(f'y_train : {y_train}')

X_train : 
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

y_train : [64 86 84 80 49 59 67 54 67]


Preprocess Dataset: Konversi Label menjadi Numerik Biner

In [60]:
X_train_transposed = np.transpose(X_train)

print(f'X_train : \n{X_train}\n')
print(f'X_train_transposed : {X_train_transposed}')

X_train : 
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

X_train_transposed : [[158 170 183 191 155 163 180 158 170]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [61]:
from sklearn.preprocessing import LabelBinarizer

lb=LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transposed[1])

print(f' jk: {X_train_transposed[1]}\n')
print(f'jk_binarised : \n{jk_binarised}')

 jk: ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binarised : 
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [64]:
jk_binarised = jk_binarised.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [65]:
X_train_transposed[1] = jk_binarised
X_train = X_train_transposed.transpose()

print(f'X_train_transposed : \n{X_train_transposed}\n')
print(f'X_train: \n{X_train}')

X_train_transposed : 
[[158 170 183 191 155 163 180 158 170]
 [0 0 0 0 1 1 1 1 1]]

X_train: 
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]


Training KNN Regression Model

In [66]:
from sklearn.neighbors import KNeighborsRegressor

K=3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                    weights='uniform')

Prediksi Berat Badan

In [67]:
X_new=np.array([[155,1]])
X_new

array([[155,   1]])

In [68]:
y_pred=model.predict(X_new)
y_pred

array([55.66666667])

Evaluasi KNN Regresi Model

In [74]:
X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

print(f'X_test : \n{X_test}\n')
print(f'y_test:{y_test}')

X_test : 
[[168   0]
 [180   0]
 [160   1]
 [169   1]]

y_test:[65 96 52 67]


In [85]:
y_pred = model.predict(X_test)
y_pred

array([77., 77., 77., 77.])

Coefficient of Determination atau R^2 (semakin mendekati 1, model semakin baik)

In [86]:
from sklearn.metrics import r2_score
r_squared = r2_score(y_test,y_pred)
r_squared

-0.1895551257253385

Mean Absolute Error (MAE) (semakin kecil nilai MAE, maka kualita model semakin baik)

In [76]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test,y_pred)

MAE

8.333333333333336

Mean Square Error MSE (Makin kecil nilai MAE, maka model akan semakin baik)

In [73]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test,y_pred)

MSE

95.8888888888889

Masalah yang dialami pada scaling feature yakni perbedaan satuan dapat berpengaruh pada jarak euclidean. Maka dari itu perlu digunakan standard scaler (atau standar score atau Z Score)




Menerapkan Feature Scaling pada KNN

In [77]:
X_train = np.array([[158,0],[170,0],[183,0],[191,0],[155,1],[163,1],[180,1],[158,1],[170,1]])
y_train = np.array([64,86,84,80,49,59,67,54,67])

X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

Feature Scaling(Standard Scaling)

In [83]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

X_train_scaled=ss.fit_transform(X_train)
X_test_scaled=ss.transform(X_test)

print(f'X_train scaled :\n{X_train_scaled}\n')
print(f'X_test_scaled: \n{X_test_scaled}\n')

X_train scaled :
[[-0.9908706  -1.11803399]
 [ 0.01869567 -1.11803399]
 [ 1.11239246 -1.11803399]
 [ 1.78543664 -1.11803399]
 [-1.24326216  0.89442719]
 [-0.57021798  0.89442719]
 [ 0.86000089  0.89442719]
 [-0.9908706   0.89442719]
 [ 0.01869567  0.89442719]]

X_test_scaled: 
[[-0.14956537 -1.11803399]
 [ 0.86000089 -1.11803399]
 [-0.82260955  0.89442719]
 [-0.06543485  0.89442719]]



Training dan Evaluasi model

In [88]:
model.fit(X_train_scaled,y_train)
y_pred = model.predict(X_test_scaled)

MAE = mean_absolute_error(y_test,y_pred)
MSE = mean_squared_error(y_test,y_pred)

print(f' MAE: \n{MAE}\n')
print(f'MSE : \n{MSE}\n')

 MAE: 
7.583333333333336

MSE : 
85.13888888888893

