<a href="https://colab.research.google.com/github/amilsiddik/machine-Learning/blob/main/06_Regression_dengan_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sample Dataset**

In [14]:
import pandas as pd

sensus = {
    'tinggi' : [158,170,183,191,155,163,180,158,178],
    'jk' :[
           'pria','pria','pria','pria','wanita','wanita','wanita','wanita','wanita'
    ],
    'berat' : [64,86,84,80,49,59,67,54,67]
}
sensus_df=pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     158    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     155  wanita     49
5     163  wanita     59
6     180  wanita     67
7     158  wanita     54
8     178  wanita     67

Features & Target

In [15]:
import numpy as np

X_train = np.array(sensus_df[['tinggi','jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_train : \n{X_train}\n')
print(f'y_train : {y_train}')

X_train : 
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

y_train : [64 86 84 80 49 59 67 54 67]


Preprocess Dataset: Konversi Label menjadi Numerik Biner

In [16]:
X_train_transposed = np.transpose(X_train)

print(f'X_train : \n{X_train}\n')
print(f'X_train_transposed : {X_train_transposed}')

X_train : 
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [178 'wanita']]

X_train_transposed : [[158 170 183 191 155 163 180 158 178]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [17]:
from sklearn.preprocessing import LabelBinarizer

lb=LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transposed[1])

print(f' jk: {X_train_transposed[1]}\n')
print(f'jk_binarised : \n{jk_binarised}')

 jk: ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binarised : 
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [18]:
jk_binarised = jk_binarised.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [19]:
X_train_transposed[1] = jk_binarised
X_train = X_train_transposed.transpose()

print(f'X_train_transposed : \n{X_train_transposed}\n')
print(f'X_train: \n{X_train}')

X_train_transposed : 
[[158 170 183 191 155 163 180 158 178]
 [0 0 0 0 1 1 1 1 1]]

X_train: 
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [178 1]]


Training KNN Regression Model

In [27]:
from sklearn.neighbors import KNeighborsRegressor

K=3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train,y_train)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                    weights='uniform')

Prediksi Berat Badan

In [21]:
X_new=np.array([[155,1]])
X_new

array([[155,   1]])

In [22]:
y_pred=model.predict(X_new)
y_pred

array([55.66666667])

Evaluasi KNN Regresi Model

In [23]:
X_test = np.array([[168,0],[180,0],[160,1],[169,1]])
y_test = np.array([65,96,52,67])

print(f'X_test : \n{X_test}\n')
print(f'y_test:{y_test}')

X_test : 
[[168   0]
 [180   0]
 [160   1]
 [169   1]]

y_test:[65 96 52 67]


In [26]:
y_pred=model.predict(X_test)
y_pred

array([69.66666667, 72.66666667, 59.        , 70.66666667])

Coefficient of Determination atau R^2

In [25]:
from sklearn.metrics import r2_score
r_squared = r2_score(y_test,y_pred)
r_squared

0.39200515796260493

Mean Absolute Error (MAE)

In [28]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test,y_pred)

MAE

9.666666666666668

Mean Square Error MSE

In [29]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test,y_pred)

MSE

157.16666666666663

Masalah yang dialami pada scaling feature yakni perbedaan satuan dapat berpengaruh pada jarak euclidean. Maka dari itu perlu digunakan standard scaler (atau standar score atau Z Score)




In [30]:
from sklearn.preprocessing import StandardScaler

ss=StandardScaler()

In [ ]:
#dalam milimeter
X_train = np.array([[1700,0],[1600,1]])
X_train_scaled = ss.fit_transform(X_train)
print(f'X_train scaled : {X_train_scaled}')

